# Nacos 配置
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # Nacos 地址
      discovery:
        namespace: dev # 命名空间 dev 环境
      config:
        namespace: dev # 命名空间 dev 环境

# XXL-Job 配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9080/xxl-job-admin # 调度中心部署跟地址
    executor:
      appname: ${spring.application.name} # 执行器 AppName
      logpath: ${user.home}/logs/xxl-job/${spring.application.name} # 执行器运行日志文件存储磁盘路径
    accessToken: default_token # 执行器通讯TOKEN