--- #################### 注册中心 + 配置中心相关配置 ####################

spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        namespace: dev
      config:
        namespace: dev

# 日志文件配置
logging:
  level:
    org.springframework.context.support.PostProcessorRegistrationDelegate: ERROR # TODO 芋艿：先禁用，Spring Boot 3.X 存在部分错误的 WARN 提示

--- #################### 服务相关配置 ####################

# 负载均衡
spring.cloud.loadbalancer.cache.enabled: false
spring.cloud.loadbalancer.retry.enabled: false
# 灰度发布 loadbalancer
gray.loadbalancer.enabled: true
